
categoryID = {
    '의복미용': {'id': 'XjNO',
             'type': 'select',
             'select': {'id': '5872ecbc-0474-4a40-8ce5-bfe61fac3d7e',
                 'name': '의복미용',
                 'color': 'brown'}},
    '꿈지출': {'id': 'XjNO',
            'type': 'select',
            'select': {'id': '9a1a50a9-4fdd-4415-8464-24ade9c58249',
                       'name': '꿈지출',
                       'color': 'yellow'}},
    '육아': {'id': 'XjNO',
           'type': 'select',
           'select': {'id': 'a53882e4-139c-4b51-87ca-e67ed7ed2b64',
                      'name': '육아',
                      'color': 'pink'}},
    '용돈': {'id': 'XjNO',
           'type': 'select',
           'select': {'id': 'b06ca5cf-9f3a-422d-9557-c33505a93153',
                      'name': '용돈',
                      'color': 'purple'}},
    '여가활동': {'id': 'XjNO',
             'type': 'select',
             'select': {'id': 'de8761a4-694f-4c2b-ac69-fa7a3240b9c5',
                        'name': '여가활동',
                        'color': 'blue'}},
    '교통': {'id': 'XjNO',
           'type': 'select',
           'select': {'id': 'a809bbb6-4787-425e-bad9-9ae6c242eac2',
                      'name': '교통',
                      'color': 'green'}},
    '기타': {'id': 'XjNO',
           'type': 'select',
           'select': {'id': '7695b898-623c-4ac6-bf8a-bc35c33d38af',
                      'name': '기타',
                      'color': 'orange'}},
    '의료': {'id': 'XjNO',
           'type': 'select',
           'select': {'id': 'd21a88da-7339-4770-9cc9-dd01a6609e65',
                      'name': '의료',
                      'color': 'gray'}},
    '생활용품': {'id': 'XjNO',
             'type': 'select',
             'select': {'id': 'b6a2e6c2-05a7-44d3-9350-aa809e5cbae1',
                        'name': '생활용품',
                        'color': 'red'}},
    '식비': {'id': 'XjNO',
           'type': 'select',
           'select': {'id': '1a567262-b111-499f-93be-598593c14932',
                      'name': '식비',
                      'color': 'default'}}
}
